pull_request_rules:
  - name: merge [bot] PRs when CI pass
    conditions:
      - or:
          - author = dependabot[bot]
          - author = gepetto-flake-updater[bot]
          - author = mc-rtc-nixpkgs-flake-updater[bot]
          - author = github-actions[bot]
          - author = pre-commit-ci[bot]
    actions:
      queue:

  - name: queue PRs with "queue" label when all CI checks pass
    conditions:
      - label = queued
    actions:
      queue:

queue_rules:
  - name: default
    conditions:
      - check-success = "check-macos-linux-nix"
      - check-success = "check-build"
      - check-success = "check-package"
