state-observation: stateObservation::tools Namespace Reference
stateObservation::tools Namespace Reference
Namespaces
Detail
Classes
class Logger
class ProbabilityLawSimulation
struct SimplestStopwatch
Functions
std::string STATE_OBSERVATION_DLLAPI matrixToString (const Matrix &mat)
std::string STATE_OBSERVATION_DLLAPI vectorToString (const Vector &v)
Matrix STATE_OBSERVATION_DLLAPI stringToMatrix (const std::string &str, Index rows, Index cols)
Vector STATE_OBSERVATION_DLLAPI stringToVector (const std::string &str, Index length)
Vector STATE_OBSERVATION_DLLAPI stringToVector (const std::string &str)
template<class T >
T square (const T &x)
computes the square of a value of any type
template<class T >
T derivate (const T &o1, const T &o2, double dt)
derivates any type with finite differences
template<typename T >
int signum (T x)
gives the sign of a variable (1, 0 or -1)
template<typename T >
std::string toString (T val)
bool checkIfNormalized (const Vector3 &v)
checks if the vector is already normalized or not
bool checkIfNormalized (const Vector3 &v, double &outputSquaredNorm)
checks if the vector is already normalized or not
template<typename T >
T clampScalar (const T &x, const T &max, const T &min)
returns the value clamped between min and max
template<typename T >
T clampScalar (const T &x, const T &limit)
returns the value clamped between limit and -limit
Vector3 normalizedLazy (const Vector3 &v)
normalize the vector only if it is not normalized already.
double STATE_OBSERVATION_DLLAPI finiteTimeAccControl (double x, double xd, double kp=-1, double kv=-1)
provides an acceleration giving a finite time convergence to zero the state is the position x and the derivative xd and the output is the acceleration.
Vector STATE_OBSERVATION_DLLAPI finiteTimeAccControl (const Vector &x, const Vector &xd, double kp=-1, double kv=-1)
sqme as the scalar version but for every member of the vector
double constexpr sqrt (double x)
Constexpr version of the square root.
Function Documentation
checkIfNormalized() [1/2]
bool stateObservation::tools::checkIfNormalized (const Vector3 & v) inline
checks if the vector is already normalized or not
Parameters
v the vector to normalize
Returns
true the vector is normalized
false The vector is not normalized
References stateObservation::cst::epsilon1.
Referenced by normalizedLazy().
checkIfNormalized() [2/2]
bool stateObservation::tools::checkIfNormalized (const Vector3 & v, double & outputSquaredNorm) inline
checks if the vector is already normalized or not
Parameters
v the vector to normalize
outputSquaredNorm the squared norm as an output
Returns
true the vector is normalized
false The vector is not normalized
References stateObservation::cst::epsilon1.
clampScalar() [1/2]
template<typename T > T stateObservation::tools::clampScalar (const T & x, const T & max, const T & min) inline
returns the value clamped between min and max
Template Parameters
T The type of the scalar
Parameters
x the input value
max the max value
min the min value
Returns
T the calmped value
Referenced by clampScalar().
clampScalar() [2/2]
template<typename T > T stateObservation::tools::clampScalar (const T & x, const T & limit) inline
returns the value clamped between limit and -limit
Template Parameters
T The type of the scalar
Parameters
x the input value
limit is the maximum absolute value allowed, has to be positive
Returns
T the clamped value
References clampScalar().
derivate()
template<class T > T stateObservation::tools::derivate (const T & o1, const T & o2, double dt) inline
derivates any type with finite differences
finiteTimeAccControl() [1/2]
double STATE_OBSERVATION_DLLAPI stateObservation::tools::finiteTimeAccControl (double x, double xd, double kp = -1, double kv = -1) inline
provides an acceleration giving a finite time convergence to zero the state is the position x and the derivative xd and the output is the acceleration.
The gains kp, kv must be negative
References signum(), and sqrt().
Referenced by finiteTimeAccControl().
finiteTimeAccControl() [2/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::finiteTimeAccControl (const Vector & x, const Vector & xd, double kp = -1, double kv = -1) inline
sqme as the scalar version but for every member of the vector
References finiteTimeAccControl().
matrixToString()
std::string STATE_OBSERVATION_DLLAPI stateObservation::tools::matrixToString (const Matrix & mat)
normalizedLazy()
Vector3 stateObservation::tools::normalizedLazy (const Vector3 & v) inline
normalize the vector only if it is not normalized already.
Useful if the vector is likely to be normalized
Parameters
v the input vector
Returns
Vector3
References checkIfNormalized(), and sqrt().
signum()
template<typename T > int stateObservation::tools::signum (T x) inline
gives the sign of a variable (1, 0 or -1)
Referenced by finiteTimeAccControl().
sqrt()
double constexpr stateObservation::tools::sqrt (double x)
Constexpr version of the square root.
For a finite and non-negative value of "x", returns an approximation for the square root of "x" -Otherwise, returns NaN
Parameters
x
Returns
double constexpr
References stateObservation::tools::Detail::sqrtNewtonRaphson().
Referenced by finiteTimeAccControl(), and normalizedLazy().
square()
template<class T > T stateObservation::tools::square (const T & x) inline
computes the square of a value of any type
stringToMatrix()
Matrix STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToMatrix (const std::string & str, Index rows, Index cols)
stringToVector() [1/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToVector (const std::string & str, Index length)
stringToVector() [2/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToVector (const std::string & str)
toString()
template<typename T > std::string stateObservation::tools::toString (T val) inline
vectorToString()
std::string STATE_OBSERVATION_DLLAPI stateObservation::tools::vectorToString (const Vector & v)