state-observation: stateObservation::tools Namespace Reference
stateObservation::tools Namespace Reference
Classes
class Logger
class ProbabilityLawSimulation
struct SimplestStopwatch
Functions
std::string STATE_OBSERVATION_DLLAPI matrixToString (const Matrix &mat)
std::string STATE_OBSERVATION_DLLAPI vectorToString (const Vector &v)
Matrix STATE_OBSERVATION_DLLAPI stringToMatrix (const std::string &str, Index rows, Index cols)
Vector STATE_OBSERVATION_DLLAPI stringToVector (const std::string &str, Index length)
Vector STATE_OBSERVATION_DLLAPI stringToVector (const std::string &str)
template<class T >
T square (const T &x)
computes the square of a value of any type
template<class T >
T derivate (const T &o1, const T &o2, double dt)
derivates any type with finite differences
template<typename T >
int signum (T x)
gives the sign of a variable (1, 0 or -1)
template<typename T >
std::string toString (T val)
double STATE_OBSERVATION_DLLAPI finiteTimeAccControl (double x, double xd, double kp=-1, double kv=-1)
provides an acceleration giving a finite time convergence to zero the state is the position x and the derivative xd and the output is the acceleration.
Vector STATE_OBSERVATION_DLLAPI finiteTimeAccControl (const Vector &x, const Vector &xd, double kp=-1, double kv=-1)
sqme as the scalar version but for every member of the vector
Function Documentation
derivate()
template<class T > T stateObservation::tools::derivate (const T & o1, const T & o2, double dt) inline
derivates any type with finite differences
finiteTimeAccControl() [1/2]
double STATE_OBSERVATION_DLLAPI stateObservation::tools::finiteTimeAccControl (double x, double xd, double kp = -1, double kv = -1) inline
provides an acceleration giving a finite time convergence to zero the state is the position x and the derivative xd and the output is the acceleration.
The gains kp, kv must be negative
References signum().
Referenced by finiteTimeAccControl().
finiteTimeAccControl() [2/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::finiteTimeAccControl (const Vector & x, const Vector & xd, double kp = -1, double kv = -1) inline
sqme as the scalar version but for every member of the vector
References finiteTimeAccControl().
matrixToString()
std::string STATE_OBSERVATION_DLLAPI stateObservation::tools::matrixToString (const Matrix & mat)
signum()
template<typename T > int stateObservation::tools::signum (T x) inline
gives the sign of a variable (1, 0 or -1)
Referenced by finiteTimeAccControl().
square()
template<class T > T stateObservation::tools::square (const T & x) inline
computes the square of a value of any type
stringToMatrix()
Matrix STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToMatrix (const std::string & str, Index rows, Index cols)
stringToVector() [1/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToVector (const std::string & str, Index length)
stringToVector() [2/2]
Vector STATE_OBSERVATION_DLLAPI stateObservation::tools::stringToVector (const std::string & str)
toString()
template<typename T > std::string stateObservation::tools::toString (T val)
vectorToString()
std::string STATE_OBSERVATION_DLLAPI stateObservation::tools::vectorToString (const Vector & v)