var namespacestateObservation =
[
    [ "algorithm", "namespacestateObservation_1_1algorithm.html", "namespacestateObservation_1_1algorithm" ],
    [ "detail", "namespacestateObservation_1_1detail.html", "namespacestateObservation_1_1detail" ],
    [ "flexibilityEstimation", "namespacestateObservation_1_1flexibilityEstimation.html", "namespacestateObservation_1_1flexibilityEstimation" ],
    [ "hrp2", "namespacestateObservation_1_1hrp2.html", "namespacestateObservation_1_1hrp2" ],
    [ "kine", "namespacestateObservation_1_1kine.html", "namespacestateObservation_1_1kine" ],
    [ "tools", "namespacestateObservation_1_1tools.html", "namespacestateObservation_1_1tools" ],
    [ "AccelerometerGyrometer", "classstateObservation_1_1AccelerometerGyrometer.html", "classstateObservation_1_1AccelerometerGyrometer" ],
    [ "AccelerometerGyrometerMagnetometer", "classstateObservation_1_1AccelerometerGyrometerMagnetometer.html", "classstateObservation_1_1AccelerometerGyrometerMagnetometer" ],
    [ "AlgebraicSensor", "classstateObservation_1_1AlgebraicSensor.html", "classstateObservation_1_1AlgebraicSensor" ],
    [ "BidimElasticInvPendulum", "classstateObservation_1_1BidimElasticInvPendulum.html", "classstateObservation_1_1BidimElasticInvPendulum" ],
    [ "CheckedItem", "classstateObservation_1_1CheckedItem.html", "classstateObservation_1_1CheckedItem" ],
    [ "CheckNaN", "structstateObservation_1_1CheckNaN.html", "structstateObservation_1_1CheckNaN" ],
    [ "DebugItem", "classstateObservation_1_1DebugItem.html", "classstateObservation_1_1DebugItem" ],
    [ "DebugItem< T, defaultValue, false >", "classstateObservation_1_1DebugItem_3_01T_00_01defaultValue_00_01false_01_4.html", "classstateObservation_1_1DebugItem_3_01T_00_01defaultValue_00_01false_01_4" ],
    [ "DebugItemDefaultValue", "classstateObservation_1_1DebugItemDefaultValue.html", null ],
    [ "DynamicalSystemFunctorBase", "classstateObservation_1_1DynamicalSystemFunctorBase.html", "classstateObservation_1_1DynamicalSystemFunctorBase" ],
    [ "DynamicalSystemSimulator", "classstateObservation_1_1DynamicalSystemSimulator.html", "classstateObservation_1_1DynamicalSystemSimulator" ],
    [ "EigenType", "structstateObservation_1_1EigenType.html", null ],
    [ "EmptyChecker", "structstateObservation_1_1EmptyChecker.html", "structstateObservation_1_1EmptyChecker" ],
    [ "ExtendedKalmanFilter", "classstateObservation_1_1ExtendedKalmanFilter.html", "classstateObservation_1_1ExtendedKalmanFilter" ],
    [ "FixOrDynMatrixTools", "classstateObservation_1_1FixOrDynMatrixTools.html", null ],
    [ "FixOrDynMatrixToolsBySize", "classstateObservation_1_1FixOrDynMatrixToolsBySize.html", null ],
    [ "FixOrDynMatrixToolsBySize< compileTimeRows, -1 >", "classstateObservation_1_1FixOrDynMatrixToolsBySize_3_01compileTimeRows_00_01-1_01_4.html", null ],
    [ "FixOrDynMatrixToolsBySize<-1, -1 >", "classstateObservation_1_1FixOrDynMatrixToolsBySize_3-1_00_01-1_01_4.html", null ],
    [ "FixOrDynMatrixToolsBySize<-1, compileTimeCols >", "classstateObservation_1_1FixOrDynMatrixToolsBySize_3-1_00_01compileTimeCols_01_4.html", null ],
    [ "GaussianWhiteNoise", "classstateObservation_1_1GaussianWhiteNoise.html", "classstateObservation_1_1GaussianWhiteNoise" ],
    [ "IMUDynamicalSystem", "classstateObservation_1_1IMUDynamicalSystem.html", "classstateObservation_1_1IMUDynamicalSystem" ],
    [ "IMUMagnetometerDynamicalSystem", "classstateObservation_1_1IMUMagnetometerDynamicalSystem.html", "classstateObservation_1_1IMUMagnetometerDynamicalSystem" ],
    [ "IMUMltpctiveDynamicalSystem", "classstateObservation_1_1IMUMltpctiveDynamicalSystem.html", "classstateObservation_1_1IMUMltpctiveDynamicalSystem" ],
    [ "IndexedMatrixArrayT", "classstateObservation_1_1IndexedMatrixArrayT.html", "classstateObservation_1_1IndexedMatrixArrayT" ],
    [ "IndexedMatrixT", "classstateObservation_1_1IndexedMatrixT.html", "classstateObservation_1_1IndexedMatrixT" ],
    [ "isEigen", "structstateObservation_1_1isEigen.html", null ],
    [ "isMatrix", "structstateObservation_1_1isMatrix.html", null ],
    [ "isMatrix< Eigen::Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >", "structstateObservation_1_1isMatrix_3_01Eigen_1_1Matrix_3_01__Scalar_00_01__Rows_00_01__Cols_00_0ef6b73255092c89cac8fa5ea734359d2.html", null ],
    [ "KalmanFilterBase", "classstateObservation_1_1KalmanFilterBase.html", "classstateObservation_1_1KalmanFilterBase" ],
    [ "KineticsObserver", "classstateObservation_1_1KineticsObserver.html", "classstateObservation_1_1KineticsObserver" ],
    [ "LinearKalmanFilter", "classstateObservation_1_1LinearKalmanFilter.html", "classstateObservation_1_1LinearKalmanFilter" ],
    [ "LipmDcmEstimator", "classstateObservation_1_1LipmDcmEstimator.html", "classstateObservation_1_1LipmDcmEstimator" ],
    [ "MatrixType", "structstateObservation_1_1MatrixType.html", null ],
    [ "NoiseBase", "classstateObservation_1_1NoiseBase.html", "classstateObservation_1_1NoiseBase" ],
    [ "ObserverBase", "classstateObservation_1_1ObserverBase.html", "classstateObservation_1_1ObserverBase" ],
    [ "SensorBase", "classstateObservation_1_1SensorBase.html", "classstateObservation_1_1SensorBase" ],
    [ "StateVectorArithmetics", "classstateObservation_1_1StateVectorArithmetics.html", "classstateObservation_1_1StateVectorArithmetics" ],
    [ "TiltEstimator", "classstateObservation_1_1TiltEstimator.html", "classstateObservation_1_1TiltEstimator" ],
    [ "TiltEstimatorHumanoid", "classstateObservation_1_1TiltEstimatorHumanoid.html", "classstateObservation_1_1TiltEstimatorHumanoid" ],
    [ "UnidimLipmDcmEstimator", "classstateObservation_1_1UnidimLipmDcmEstimator.html", "classstateObservation_1_1UnidimLipmDcmEstimator" ],
    [ "ZeroDelayObserver", "classstateObservation_1_1ZeroDelayObserver.html", "classstateObservation_1_1ZeroDelayObserver" ],
    [ "ZmpTrackingGainEstimator", "classstateObservation_1_1ZmpTrackingGainEstimator.html", "classstateObservation_1_1ZmpTrackingGainEstimator" ]
];